### ISSUE TITLE
docker-compose container linking and networking issues in new Trusty images 

### ISSUE THREAD

**Issue by Lyoness** [travis-ci/packer-templates#234]
https://secure.helpscout.net/conversation/237208698/33253/?folderId=30788
https://secure.helpscout.net/conversation/236948980/33121/?folderId=30788

https://github.com/travis-ci/travis-ci/issues/6461

**Comment by meatballhat** [comment]
I'm not clear on what the fix is here 😐.  It looks to me like folks depending on docker =~ 1.9.x are getting a variety of errors on docker =~ 1.12.x.  @solarce provided a snippet for folks to downgrade if needed, and I'm generally :-1: to downgrading the version that's baked into the image(s).  What should we do?

**Comment by Lyoness** [comment]
Agreed, effectively a problem with docker version update.


Downgrade instructions here as a quick fix. 
https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-239577306

Will need to upgrade docs for trusty stacks with `service: docker` Closing.
