### ISSUE TITLE
Update JRuby to 9.x.x

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#391]
https://twitter.com/mperham/status/816005300062863362

Ideally, we can offer a recent version of 1.7.x, because it is one that offers Ruby 1.9.x compatibility.

Related:
https://github.com/travis-ci/travis-ci/issues/6185
https://github.com/travis-ci/travis-ci/issues/6123

**Comment by perlun** [comment]
I don't know about other people, but for me, a recent JRuby 9.x is more important than a JRuby 1.7.x since 1.7.x has reached EOL anyway (and we are moving as many apps as possible away from it).

**Comment by meatballhat** [comment]
@BanzaiMan AFAICT this is already done for all Trusty stacks with preinstalled JRuby, although the production container-based Trusty stacks lag behind sudo-enabled by a release or so, which will be resolved in the next build environment update so that they both look like so:

https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/194691559#L228-L229

**Comment by perlun** [comment]
> AFAICT this is already done for all Trusty stacks with preinstalled JRuby, although the production container-based Trusty stacks lag behind sudo-enabled by a release or so,

Nice stuff! 👏 I guess there isn't any beta version for the non-sudo environments you can opt in to yet? 😉

**Comment by perlun** [comment]
@meatballhat Any updates on this?

**Comment by perlun** [comment]
@meatballhat Are we alive? 😉 

We're eagerly awaiting this PR to land. Travis is still utterly slow on installing JRubies. 😢

**Comment by meatballhat** [comment]
@perlun Sorry for my laggy response!  I'm still working on stabilizing some other bits prior to rolling out the full build env update, but you can test this out by specifying `group: edge` on sudo-enabled Linux.

**Comment by perlun** [comment]
Ah, I guess the trick is specifying the `rvm: jruby` line as well (https://github.com/meatballhat/cloaked-octo-tyrion/blob/ec2-trusty-jruby/.travis.yml#L2)... Will add that now.

**Comment by perlun** [comment]
@meatballhat - great work thus far! 9.1.2.0 is almost a year old though (released in March 2016). I guess you could quite easily bump it to the latest and greatest 9.1.7.0 since we're talking about yet unreleased stuff anyway? (it makes little sense to release something which is a year old at the date of release. 😄)

**Comment by perlun** [comment]
@meatballhat sorry, I just can't get it working. 😢 No matter how I try, I can't get it to run on the right image.

This was my last, feeble attempt: 

```
language: ruby
rvm: jruby
dist: trusty
sudo: required
group: edge
```

It still doesn't have JRuby 9.x preinstalled. What do I do wrong?

**Comment by perlun** [comment]
@meatballhat Any suggestions?

**Comment by perlun** [comment]
Ping @meatballhat

**Comment by perlun** [comment]
FWIW, I decided to implement this workaround for now: https://gist.github.com/perlun/a20924957203d4fc202e9b6523d79598

By skipping RVM and just downloading the binaries directly, we are down from 100-200 seconds to about 10s (including`gem install bundler`).

**Comment by perlun** [comment]
@meatballhat status on this would be nice also. Has it been implemented in `stable`, does it only work on `edge`, what version do we get, etc...?
